export DOTFILES="${HOME}/coding/dotfiles/macos"

export CACHEDIR="$HOME/.local/share"

[[ -d "$CACHEDIR" ]] || mkdir -p "$CACHEDIR"

export EDITOR='nvim'
export GIT_EDITOR='nvim'

# source all environment variables
source "${DOTFILES}/zsh/variables.zsh"

# launch ssh-agent is not running yet
# if [ -z "$SSH_AUTH_SOCK" ] ; then
#  echo "ssh-agent seems to be stopped, launch one"
#  eval $(ssh-agent -s)

  # OSX onl`y
  # store passphrase in keychain, so that key password is unlocked by local user password
  # do this once during system install
  # ssh-add -K $KEYFILES
# fi
