# load fzf settings
source $DOTFILES/zsh/zplug.zsh
source $DOTFILES/zsh/fzf.zsh

# key-binding for zsh-history-substring-search 
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# load aliases 
source $DOTFILES/zsh/aliases.zsh

#  load pyenv 
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

#  mysql 5.6 
source $DOTFILES/zsh/mysql5.6.zsh

