# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH


export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

# zplug
export ZPLUG_HOME=$HOME/.zplug
source "${ZPLUG_HOME}/init.zsh"
zplug 'plugins/git', from:oh-my-zsh, if:'which git'
zplug 'plugins/vi-mode', from:oh-my-zsh
zplug 'plugins/tmux', from:oh-my-zsh
zplug 'wting/autojump', from:oh-my-zsh
zplug 'zsh-users/zsh-autosuggestions'
zplug 'zsh-users/zsh-completions', defer:2
zplug 'zsh-users/zsh-history-substring-search'
zplug 'zsh-users/zsh-syntax-highlighting', defer:2
if ! zplug check; then
  zplug install
fi
zplug load


source $ZSH/oh-my-zsh.sh

# ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=6

# autojump script ,used by wting/autojump
[[ -s $HOME/.autojump/etc/profile.d/autojump.sh ]] && source $HOME/.autojump/etc/profile.d/autojump.sh
autoload -U compinit && compinit -u


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# Configure fzf, command line fuzzyf finder
FD_OPTIONS="--hidden --follow --exclude .git --exclude node_modules "
export FZF_DEFAULT_OPTS="--no-mouse --height 50% -1 --reverse --multi --inline-info --preview='[[ \$(file --mime {}) =~ binary ]] && echo {} is a binary file || (bat --style=numbers --color=always {} || cat {}) 2> /dev/null | head -300' --preview-window='right:hidden:wrap' --bind='f3:execute(bat --style=numbers {} || less -f {}),f2:toggle-preview,ctrl-d:half-page-down,ctrl-u:half-page-up,ctrl-a:select-all+accept,ctrl-y:execute-silent(echo {+} | pbcopy),ctrl-x:execute(rm -i {+})+abort'"
# Use git-ls-files inside git repo, otherwise fd ,fdfind on Ubuntu = fd on mac
export FZF_DEFAULT_COMMAND="git ls-files --cached --others --exclude-standard || fdfind --type f --type l $FD_OPTIONS"
export FZF_CTRL_T_COMMAND="fdfind $FD_OPTIONS"
export FZF_ALT_C_COMMAND="fdfind --type d $FD_OPTIONS"