# aliases 
alias sshc7='ssh ckt@c7work'
alias pip3='/usr/local/bin/python3 -m pip'
alias venv='/usr/local/bin/python3 -m venv --copies '
#alias vim='nvim'



# remove sticky bg color
eval "$(dircolors -p | \
    sed 's/ 4[0-9];/ 01;/; s/;4[0-9];/;01;/g; s/;4[0-9] /;01 /' | \
    dircolors /dev/stdin)"

# when filter https package using wireshark. uncomment below
#export SSLKEYLOGFILE="/Users/akin/tls/sslkeylog.log"

# export PATH="/usr/local/opt/openssl@1.1/bin:$PATH" 
# export PATH="/usr/local/opt/openjdk/bin:$PATH"
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="/home/ckt/.pyenv/bin:$PATH"
export PATH="/usr/local/opt/sqlite/bin:$PATH"
export PATH="/usr/local/opt/openssl/bin:$PATH"
export PATH="/usr/local/opt/mysql/bin:$PATH"
export PATH="/usr/local/mysql/bin:$PATH"
export PATH="/usr/local/opt/redis@4.0/bin:$PATH"
export PATH="/usr/local/opt/mongodb-community@4.0/bin:$PATH"
export PATH="/usr/local/opt/mysql-client/bin:$PATH"


# export CFLAGS="${CFLAGS} -I/usr/local/include/mysql"
# export CFLAGS="-I/usr/local/opt/openssl@1.1/include"
# export CFLAGS="${LDFLAGS} -I/Users/akin/openssl102a/include"
# export CFLAGS="-I$(brew --prefix openssl)/include" 
# export CPPFLAGS="-I/usr/local/opt/sqlite/include"
# export CPPFLAGS="${CPPFLAGS} -I/usr/local/include/mysql"
# export CPPFLAGS="${LDFLAGS} -I/Users/akin/openssl102a/include"
#export CPPFLAGS="-I/usr/local/opt/mysql@5.6/include"
#export CPPFLAGS="-I/usr/local/opt/openssl/include $CPPFLAGS"
#export CPPFLAGS="-I/usr/local/opt/mysql-connector-c\+\+@1.1/include $CPPFLAGS"
# export LDFLAGS="-L/usr/local/opt/sqlite/lib"
# export LDFLAGS="-L$(brew --prefix openssl)/lib" 
# export LDFLAGS="${LDFLAGS} -L/usr/local/lib"
# export LDFLAGS="${LDFLAGS} -L/Users/akin/openssl102a/lib"
#export LDFLAGS="-L/usr/local/opt/mysql@5.6/lib"
#export LDFLAGS="-L/usr/local/opt/mysql-connector-c\+\+@1.1/lib  $LDFLAGS"
#export LDFLAGS="-L/usr/local/opt/openssl/lib  $LDFLAGS"
#export DYLD_LIBRARY_PATH=/usr/local/mysql/lib:$DYLD_LIBRARY_PATH

# export PKG_CONFIG_PATH="${PKG_CONFIG_PATH} /usr/local/opt/mysql/lib/pkgconfig"
#export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig $PKG_CONFIG_PATH"

# for python compilation
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Path to your oh-my-zsh installation.
export ZSH="/home/ckt/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
# ZSH_THEME="muse"
ZSH_THEME="cloud"
# ZSH_THEME="agnoster" # not compatable


# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#plugins=(git autojump vi-mode tmux zsh-autosuggestions zsh-completions history-substring-search zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=C
# export LANG=zh_CN.UTF-8
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# zplug
export ZPLUG_HOME=$HOME/.zplug
source "${ZPLUG_HOME}/init.zsh"
zplug 'plugins/git', from:oh-my-zsh, if:'which git'
zplug 'plugins/vi-mode', from:oh-my-zsh
zplug 'plugins/tmux', from:oh-my-zsh
zplug 'wting/autojump', from:oh-my-zsh
zplug 'zsh-users/zsh-autosuggestions'
zplug 'zsh-users/zsh-completions', defer:2
zplug 'zsh-users/zsh-history-substring-search'
zplug 'zsh-users/zsh-syntax-highlighting', defer:2
if ! zplug check; then
  zplug install
fi
zplug load


# ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=6

# auto jump script
[[ -s /home/ckt/.autojump/etc/profile.d/autojump.sh ]] && source /home/ckt/.autojump/etc/profile.d/autojump.sh
autoload -U compinit && compinit -u
