set rnu
set nu
set clipboard=unnamed
set statusline+=%F
set path +=autoload
set path +=**
set wildmenu
set tags=tags
nnoremap Y y$
nnoremap V v$

let mapleader = ','

set splitbelow
set splitright

map <C-t> :NERDTreeToggle<CR>

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
map <S-f> :CtrlPMRU<CR>   
set wildmode=longest,list
set wildignore+=*.a,*.o
set wildignore+=*.DS_Store,.git,.hg,.svn
set wildignore+=*~,*.swp,*.tmp
set wildignore+=*.bmp,*.jpg,*.png,*.gif,*.ico
set wildignore+=*.pyc,*.pyo,*.pyd


" map settings 
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l
nmap <C-\>\ <C-w>v
nmap <C-\>= <C-w>s
map <C-b> :browse oldfiles<CR> 
map <C-n> <C-e>
map <C-p> <C-y>


set nocompatible " be iMproved, required
filetype off " required
 
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plugin 'junegunn/fzf.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-sensible'
Plugin 'lifepillar/vim-solarized8'
Plugin 'dracula/vim', { 'name': 'dracula' }
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'tomasr/molokai'
Plugin 'morhetz/gruvbox'
call vundle#end() " required 

" set Vim-specific sequences for RGB colors
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

filetype plugin indent off " required

" set background=dark
colorscheme molokai

" set backgroud transparency
hi Normal guibg=NONE ctermbg=NONE

" fzf 
" Mapping selecting mappings
let g:fzf_command_prefix = 'Fzf'
nmap <leader><tab> <plug>(fzf-maps-n)
xmap <leader><tab> <plug>(fzf-maps-x)
omap <leader><tab> <plug>(fzf-maps-o)
nnoremap <silent> <leader>o :FzfFiles<CR>
nnoremap <silent> <leader>O :FzfFiles!<CR>
nnoremap <silent> <leader>h :FzfHistory<CR>
nnoremap <silent> <leader>: :FzfHistory:<CR>
nnoremap <silent> <leader>/ :FzfHistory/<CR>
nnoremap <silent> <leader>b :FzfBuffers<CR>
nnoremap <silent> <leader>; :FzfCommands<CR>
nnoremap <silent> <leader>l :FzfBlines<CR>
nnoremap <silent> <leader>m :FzfMarks<CR>
nnoremap <silent> <leader>s :FzfSnippets<CR>
nnoremap <silent> <F1> :FzfHelptags<CR>
inoremap <silent> <F1><ESC> :FzfHelptags<CR>

nnoremap <silent> <leader>T :FzfTags<CR>
nnoremap <silent> <leader>t :FzfBTags<CR>

" Insert mode completion
imap <c-x><c-k> <plug>(fzf-complete-word)
imap <c-x><c-f> <plug>(fzf-complete-path)
imap <c-x><c-j> <plug>(fzf-complete-file-ag)
imap <c-x><c-l> <plug>(fzf-complete-line)

" Advanced customization using Vim function
inoremap <expr> <c-x><c-k> fzf#vim#complete#word({'left': '15%'})

" tagbar 
nnoremap <silent> <Leader>b :TagbarToggle<CR>

" ultisniips
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

" deoplete 
let g:deoplete#enable_at_startup = 1
