export ZSH="/Users/akin/.oh-my-zsh"

ZSH_THEME="bira"

plugins=(autojump 
         vi-mode 
         tmux 
         git
         zsh-autosuggestions 
         zsh-completions 
         history-substring-search 
         zsh-syntax-highlighting)

# when filter https package using wireshark. uncomment below
export SSLKEYLOGFILE="$HOME/tls/sslkeylog.log"
export python3="$HOME/.pyenv/shims/python3"

source $ZSH/oh-my-zsh.sh

#eval "$(pyenv init -)"
#eval "$(pyenv virtualenv-init -)"

# fzf settings
export FD_OPTION="--follow --exclude .git --exclude node_modules --exclude __pycache__ "
export FZF_DEFAULT_OPTS='--layout=reverse --border'
export FZF_DEFAULT_COMMAND="fd --type f $FD_OPTION"
export FZF_CTRL_T_COMMAND="fd $FD_OPTION"
export FZF_ALT_C_COMMAND="fd --type d $FD_OPTION"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# iterm option c issue fix
bindkey "ç" fzf-cd-widget

