export LANG="en_US.UTF-8"
export HISTSIZE=10000
export SAVEHIST=$HISTSIZE
# Command history configuration
if [ -z "$HISTFILE" ]; then
    HISTFILE=$HOME/.zsh_history
fi

# Show history
case $HIST_STAMPS in
  "mm/dd/yyyy") alias history='fc -fl 1' ;;
  "dd.mm.yyyy") alias history='fc -El 1' ;;
  "yyyy-mm-dd") alias history='fc -il 1' ;;
  *) alias history='fc -l 1' ;;
esac

setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
#setopt share_history # share command history data

# import aliases
[  -f $HOME/.aliases ] && source $HOME/.aliases

export ZPLUG_HOME=$HOME/.zplug
source $ZPLUG_HOME/init.zsh
zplug 'zplug/zplug', hook-build:'zplug --self-manage'
zplug "themes/bira", as:theme, from:oh-my-zsh
zplug "plugins/vi-mode", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/tmux", from:oh-my-zsh
zplug "plugins/autojump", from:oh-my-zsh
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "lib/completion", from:oh-my-zsh
# zplug "zdharma/fast-syntax-highlighting"
zplug "zsh-users/zsh-history-substring-search"
zplug "b4b4r07/emoji-cli"
# fzf
zplug 'junegunn/fzf', \
      as:command, \
      use:'bin/{fzf,fzf-tmux}', \
      if:"[[ $OSTYPE == linux* || $OSTYPE == darwin* ]]", \
      hook-build:'./install --key-bindings --completion --no-update-rc', \
      defer:2
zplug "junegunn/fzf", from:github, use:"shell/completion.zsh", defer:2 
zplug "junegunn/fzf", from:github, use:"shell/key-bindings.zsh", defer:2 

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# load plugins
# zplug load --verbose 
zplug load --verbose 

# zplug check returns true if the given repository exists
if zplug check b4b4r07/enhancd; then
    # setting if enhancd is available
    export ENHANCD_FILTER=fzf-tmux
fi


# Fzf options
export FD_OPTION=" --hidden --follow --exclude .git --exclude node_modules --exclude __pycache__ "
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS" --layout=reverse --inline-info --height=50% "
export FZF_DEFAULT_COMMAND="fd --type f $FD_OPTION"
export FZF_CTRL_T_COMMAND="fd $FD_OPTION"
export FZF_ALT_C_COMMAND="fd --type d $FD_OPTION"

# # Exclude those directories even if not listed in .gitignore, or if .gitignore is missing
# FD_OPTIONS="--follow --exclude .git --exclude node_modules"

# # Change behavior of fzf dialogue
# export FZF_DEFAULT_OPTS="--no-mouse --height 50% -1 --reverse --multi --inline-info --preview='[[ \$(file --mime {}) =~ binary ]] && echo {} is a binary file || (bat --style=numbers --color=always {} || cat {}) 2> /dev/null | head -300' --preview-window='right:hidden:wrap' --bind='f3:execute(bat --style=numbers {} || less -f {}),f2:toggle-preview,ctrl-d:half-page-down,ctrl-u:half-page-up,ctrl-a:select-all+accept,ctrl-y:execute-silent(echo {+} | pbcopy)'"

# # Change find backend
# # Use 'git ls-files' when inside GIT repo, or fd otherwise
# export FZF_DEFAULT_COMMAND="git ls-files --cached --others --exclude-standard | fd --type f --type l $FD_OPTIONS"

# # Find commands for "Ctrl+T" and "Opt+C" shortcuts
# export FZF_CTRL_T_COMMAND="fd $FD_OPTIONS"
# export FZF_ALT_C_COMMAND="fd --type d $FD_OPTIONS"

# When filter https package using wireshark. uncomment below
#export SSLKEYLOGFILE="$HOME/tls/sslkeylog.log"
#export python3="$HOME/.pyenv/shims/python3"

# key-binding for zsh-history-substring-search 
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# Pycharm path
export PATH=$HOME/jetbrains:$PATH


